import mongoose from 'mongoose';

const { Schema } = mongoose;

// Notification — inbox items generated by real platform events. Two audiences:
// ADMIN (shared inbox: support tickets, approval queues, refund requests…) and
// ORGANIZER (per-user inbox via `userId`: bookings, event approvals/rejections,
// refunds on their events…). `link` is the client route the header bell opens
// on click; `read` flips when the recipient opens or clears the item.
const notificationSchema = new Schema(
  {
    audience: { type: String, enum: ['ADMIN', 'ORGANIZER'], default: 'ADMIN' },
    userId: { type: Schema.Types.ObjectId, ref: 'User' }, // recipient (ORGANIZER audience)
    type: { type: String, required: true },
    title: { type: String, required: true },
    body: String,
    link: { type: String, required: true },
    entityType: String,
    entityId: { type: Schema.Types.ObjectId },
    read: { type: Boolean, default: false },
  },
  { timestamps: true }
);

notificationSchema.index({ audience: 1, read: 1, createdAt: -1 });
notificationSchema.index({ audience: 1, createdAt: -1 });
notificationSchema.index({ userId: 1, read: 1, createdAt: -1 });

export default mongoose.model('Notification', notificationSchema);
