import mongoose from 'mongoose';

const { Schema } = mongoose;

// Notification — admin inbox items generated by real platform events (support
// tickets, approval queues, refund requests, organizer applications, partner
// leads). `link` is the client route the header bell opens on click; `read`
// flips when an admin opens or clears the item.
const notificationSchema = new Schema(
  {
    audience: { type: String, enum: ['ADMIN'], default: 'ADMIN' },
    type: { type: String, required: true },
    title: { type: String, required: true },
    body: String,
    link: { type: String, required: true },
    entityType: String,
    entityId: { type: Schema.Types.ObjectId },
    read: { type: Boolean, default: false },
  },
  { timestamps: true }
);

notificationSchema.index({ audience: 1, read: 1, createdAt: -1 });
notificationSchema.index({ audience: 1, createdAt: -1 });

export default mongoose.model('Notification', notificationSchema);
