// Portal icon set — thin wrappers around Lucide React so every admin/organizer
// surface shares one consistent, premium stroke style. The AdminIcon.<Name> API
// is unchanged from the hand-built set it replaces, so callers keep working.
import {
  LayoutDashboard,
  Briefcase,
  CalendarDays,
  RotateCcw,
  CreditCard,
  Users,
  Tag,
  Globe,
  FileText,
  Image,
  BarChart3,
  Mic,
  Award,
  Mail,
  Search,
  ExternalLink,
  LogOut,
  Plus,
  PenLine,
  Trash2,
  Check,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Menu,
  AlertTriangle,
  Eye,
  EyeOff,
  Star,
  ArrowUpRight,
  ArrowRight,
  Download,
  Home,
  Bell,
  Ticket,
  MessageCircle,
  RefreshCw,
  Settings,
  HelpCircle,
  Moon,
  Sun,
  PanelLeftClose,
  PanelLeftOpen,
  Command,
  Zap,
  Clock,
  MoreHorizontal,
  TrendingUp,
  TrendingDown,
  MapPin,
  Activity,
  Info,
  Copy,
  Send,
  Wallet,
  ShieldCheck,
  Percent,
  Megaphone,
  ScrollText,
  Sparkles,
  Filter,
  Inbox,
  QrCode,
  IndianRupee,
  CheckCircle2,
  XCircle,
  CalendarClock,
  UserRound,
  KeyRound,
  Lock,
} from 'lucide-react';

// Default 18px @ 1.75 stroke reads crisp at dashboard densities; callers can
// override both via props exactly like before.
const w = (Ic) =>
  function Icon({ size = 18, strokeWidth = 1.75, ...rest }) {
    return <Ic size={size} strokeWidth={strokeWidth} aria-hidden="true" {...rest} />;
  };

export const AdminIcon = {
  Dashboard: w(LayoutDashboard),
  Organizers: w(Briefcase),
  Events: w(CalendarDays),
  Refunds: w(RotateCcw),
  Transactions: w(CreditCard),
  Users: w(Users),
  Categories: w(Tag),
  Chapters: w(Globe),
  Cms: w(FileText),
  Hero: w(Image),
  Reports: w(BarChart3),
  Speakers: w(Mic),
  Sponsors: w(Award),
  Mail: w(Mail),
  Search: w(Search),
  External: w(ExternalLink),
  Logout: w(LogOut),
  Plus: w(Plus),
  Edit: w(PenLine),
  Trash: w(Trash2),
  Check: w(Check),
  Close: w(X),
  ChevronDown: w(ChevronDown),
  ChevronRight: w(ChevronRight),
  ChevronLeft: w(ChevronLeft),
  Menu: w(Menu),
  Warning: w(AlertTriangle),
  Eye: w(Eye),
  EyeOff: w(EyeOff),
  Star: w(Star),
  ArrowUpRight: w(ArrowUpRight),
  ArrowRight: w(ArrowRight),
  Download: w(Download),
  Home: w(Home),
  Bell: w(Bell),
  Ticket: w(Ticket),
  Comment: w(MessageCircle),
  Refresh: w(RefreshCw),
  // ── additions for the redesigned shells & dashboards ──
  Settings: w(Settings),
  Help: w(HelpCircle),
  Moon: w(Moon),
  Sun: w(Sun),
  Collapse: w(PanelLeftClose),
  Expand: w(PanelLeftOpen),
  Command: w(Command),
  Zap: w(Zap),
  Clock: w(Clock),
  More: w(MoreHorizontal),
  TrendUp: w(TrendingUp),
  TrendDown: w(TrendingDown),
  MapPin: w(MapPin),
  Activity: w(Activity),
  Info: w(Info),
  Copy: w(Copy),
  Send: w(Send),
  Wallet: w(Wallet),
  Shield: w(ShieldCheck),
  Percent: w(Percent),
  Megaphone: w(Megaphone),
  Scroll: w(ScrollText),
  Sparkles: w(Sparkles),
  Filter: w(Filter),
  Inbox: w(Inbox),
  QrCode: w(QrCode),
  Rupee: w(IndianRupee),
  CheckCircle: w(CheckCircle2),
  XCircle: w(XCircle),
  CalendarClock: w(CalendarClock),
  User: w(UserRound),
  Key: w(KeyRound),
  Lock: w(Lock),
};

export default AdminIcon;
